apiVersion: v1
kind: Pod
metadata:
  name: verybusy
spec:
  containers:
    - name: busy
      image: busybox
      command:
        - sleep
        - "3600"
    - name: box
      image: busybox
      command:
        - sleep
        - "3600"
