apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: escalable-nginx
  name: escalable-nginx
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: escalable-nginx
status:
  loadBalancer: {}
